apiVersion: apps/v1
kind: Deployment
metadata:
 name: ibmcloudwebapp
 labels:
    app: ibmcloudwebapp
spec:
 replicas: 2
 selector:
    matchLabels:
      app: ibmcloudwebapp
 template:
    metadata:
       labels:
        app: ibmcloudwebapp
    spec:
      containers:
      - name: ibmcloudwebappcontainer
        image: us.icr.io/ibmperumf/ibmcloudwebapp:latest
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: ibmcloudwebapp
spec:
 type: NodePort
 selector:
   app: ibmcloudwebapp
 ports:
   - name: client
     protocol: TCP
     port: 8080
     nodePort: 32089
 selector:
   app: ibmcloudwebapp
